In [10]:
# 1. Parameters and setup

beta    = 0.87
delta   = 0.06
gamma   = 2
alpha   = 0.35
wage    = 1
za      = 1
epsilon = 3
mu      = epsilon/(epsilon - 1)
D       = 1

In [11]:
# Overhead labor
phil   = 0.00  # Baseline model
#phil  = 0.135 # Robustness check with overhead labor

In [17]:
import numpy as np
# Permanent productivity differences
nzp = 2
zp_sd_target = 0.43 # Target standard deviation
piL = 0.80
zLspace = np.linspace(0.0001,0.9999,1000000)
difference = piL*(zLspace-1)**2 + (1-piL)*((piL-piL*zLspace)/(1-piL))**2-zp_sd_target**2

# Find index of minimum absolute difference
index = np.argmin(np.abs(difference))
zp_l  = zLspace[index]
zp_h  = (1-piL*zp_l) / (1-piL)
zp_grid = [zp_l, zp_h]

# Create zpprob matrix
zpprob = np.eye(nzp)

# Print zp_l, zp_h, and zpprob
print("zp_l:", zp_l)
print("zp_h:", zp_h)
print("zpprob:\n", zpprob)

zp_l: 0.7849997736997737
zp_h: 1.8600009052009052
zpprob:
 [[1. 0.]
 [0. 1.]]


In [14]:
# For extension with exogeneous labor wedges
ntau = 1 # Baseline model has ntau = 1, extension with exogeneous labror wedges has ntau = 2
if ntau ==2:
    tau_grid = np.linspace(-0.29,0.29,ntau)
    tauprob  = np.array([[0.81,0.19],[0.19,0.81]])
elif ntau == 1:
    tau_grid = np.array([0.00])
    tauprob   = np.array([1])
# Print tau_grid and tauprob
print("tau_grid:", tau_grid)
print("tauprob:\n", tauprob)


tau_grid: [0.]
tauprob:
 [1]


In [15]:
# For extension with unmeasured capital
nq = 1 # Baseline model has nq = 1, extension with unmeasured capital has nq = 2
if nq == 2:
    q_grid = np.linspace(-0.18,0.18,nq)
    qprob  = np.eye(nq)
elif nq == 1:
    q_grid = np.array([0.00])
    qprob  = np.array([1])
# Print q_grid and qprob
print("q_grid:", q_grid)
print("qprob:\n", qprob)

q_grid: [0.]
qprob:
 [1]


In [16]:
# Transitory log productivity shocks
from quantecon import tauchen

# Paramters for the zt process
nzt = 11
rho_zt = 0.59
sigma_zt = 0.13
mu_zt = -(sigma_zt**2) / (2 * (1+rho_zt))

# Generate discretized Markov chain for transitory log productivity shocks
mc = tauchen(rho=rho_zt, sigma=sigma_zt,mu=mu_zt,n=nzt,n_std=3)
zt_grid = mc.state_values
ztprob = mc.P

# Print zt_grid and ztprob
print("zt_grid:", zt_grid)
print("ztprob:\n", ztprob)

zt_grid: [-0.49599212 -0.39938612 -0.30278012 -0.20617412 -0.10956811 -0.01296211
  0.08364389  0.18024989  0.2768559   0.3734619   0.4700679 ]
ztprob:
 [[1.24693249e-01 2.16680171e-01 2.89589745e-01 2.28414720e-01
  1.06292197e-01 2.91528811e-02 4.70536022e-03 4.46070010e-04
  2.47855932e-05 8.05489206e-07 1.54493145e-08]
 [5.58854662e-02 1.42567414e-01 2.60117020e-01 2.80046562e-01
  1.77929763e-01 6.66743172e-02 1.47170492e-02 1.91023873e-03
  1.45507188e-04 6.49063318e-06 1.71789610e-07]
 [2.12431003e-02 7.80477317e-02 1.94453157e-01 2.85767237e-01
  2.47844240e-01 1.26832227e-01 3.82631569e-02 6.79514017e-03
  7.09043440e-04 4.33810649e-05 1.58580212e-06]
 [6.80930931e-03 3.55404978e-02 1.20965676e-01 2.42702862e-01
  2.87315907e-01 2.00732008e-01 8.27246048e-02 2.00872103e-02
  2.86916570e-03 2.40593985e-04 1.21643282e-05]
 [1.83268227e-03 1.34576001e-02 6.26060163e-02 1.71547201e-01
  2.77218312e-01 2.64369300e-01 1.48772522e-01 4.93655808e-02
  9.64543118e-03 1.10772221e-03 7.7

In [20]:
import numpy as np
# Interest rate process
runexp = 1 # =1, all changes in r are unexpected (baseline), =1, AR(1) process
nr     = 6
r_grid = [0.01,0.02,0.03,0.04,0.05,0.10]
if runexp == 1:
    rprob = np.eye(nr)
elif runexp == 0:
    # Initial drop unexpected and then from AR(1) process between 1994-2011
    rho_r = 0.50
    sigma_r = 0.0086
    mu_r    = 0.03*rho_r
    r_grid_temp, rprob_temp = tauchen(rho=rho_r,sigma=sigma_r,mu=mu_r,n=nr-1,n_std=2.014)
    r_grid = np.append(r_grid_temp, max(r_grid_temp))
    rprob = np.hstack((rprob_temp, np.zeros((nr-1,1))))
    rprob = np.vstack((rprob,[0.00,0.00,0.00,0.00,0.00,1.00]))

# Print r_grid and rprob
print("r_grid:", r_grid)
print("rprob:\n", rprob)

r_grid: [0.01, 0.02, 0.03, 0.04, 0.05, 0.1]
rprob:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
# Financial frictions parameters in collateral constraint: k' < chi0 * a + chi1 * (exp(k') - 1)

# Baseline HeF model:
chi0_baseline = 0.98
chi1_baseline = 0.047

# Standard model with homogeneous frictions (HoF):
# chi0_standard = 1.06
# chi1_standard = 0.00

# No financial frictions (NoF) model:
# chi0_nof = 10**10
# chi1_nof = 0

# Adjustment costs calibrated to match K response 99-07:
# chi0_adjusted = 0.98
# chi1_adjusted = 0.047

# Extension of HeF model recalibrated to overhead labor:
# chi0_overhead_labor = 0.98
# chi1_overhead_labor = 0.047

# Extension of HeF model recalibrated to exogenous labor wedge shocks:
# chi0_exogenous_labor = 1.01
# chi1_exogenous_labor = 0.050

# Extension of HeF model recalibrated to unmeasured capital:
# chi0_unmeasured_capital = 1.01
# chi1_unmeasured_capital = 0.037

# Extension of HeF model with AR(1) process for r:
# chi0_ar1_process = 1.02
# chi1_ar1_process = 0.042

In [ ]:
# Adjustment cost parameter
# psi = 3.2    # baseline model HeF
# psi = 3.2    # model HoF
# psi = 3.5    # model NoF
# psi = 7.6    # adjustment costs calibrated to match K response 99-07
# psi = 3.2    # model recalibrated to overhead labor
# psi = 2.3    # model recalibrated to exogenous labor wedge shocks
# psi = 1.6    # model recalibrated to unmeasured capital
# psi = 3.1    # model with AR(1) process for r

In [21]:
# Grids for capital and net worth
k_l = 0.01
k_h = 6.0
nk = 120
k_grid = np.linspace(k_l, k_h, nk)

a_l = 0.01
a_h = 3.0
na = 120
a_grid = np.linspace(a_l, a_h, na)

n_choice = nk * na
n_state = nzp * nzt * nr * ntau * nq

In [67]:
# Create matrices for zp, zt, r, tau, q, a, and k
q_grid_ind = np.array(list(range(1,nq+1)))
tau_grid_ind = np.array(list(range(1,ntau+1)))
r_grid_ind   = np.array(list(range(1,nr+1)))
zt_grid_ind  = np.array(list(range(1,nzt+1)))
zp_grid_ind  = np.array(list(range(1,nzp+1)))

# Create matrices Q and Q_ind
Q = np.tile(np.expand_dims(q_grid, axis = 1),(nzp*nzt*nr*ntau,1))
Q_ind = np.tile(np.expand_dims(q_grid_ind, axis = 1),(nzp*nzt*nr*ntau,1))

# Create matrices TAU and TAU_ind
TAU = np.tile(np.expand_dims(tau_grid,axis=1),(nq,1))
TAU = np.sort(TAU, axis=1)
TAU = np.tile(np.expand_dims(TAU,axis=1),(nzp*nzt*nr,1))

TAU_ind = np.tile(np.expand_dims(tau_grid_ind,axis=1),(nq,1))
TAU_ind = np.sort(TAU_ind,axis=1)
TAU_ind = np.tile(np.expand_dims(TAU_ind,axis=1),(nzp*nzt*nr,1))

# Create matrices R and R_ind
R = np.tile(np.expand_dims(r_grid,axis=1),(ntau*nq,1))
R = np.sort(R,axis=1)
R = np.tile(np.expand_dims(R,axis=1),(nzp*nzt,1))

R_ind = np.tile(np.expand_dims(r_grid_ind,axis=1),(ntau*nq,1))
R_ind = np.sort(R_ind,axis=1)
R_ind = np.tile(np.expand_dims(R_ind,axis=1),(nzp*nzt,1))

# Create matrices ZT and ZT_ind
ZT = np.tile(np.expand_dims(zt_grid,axis=1),(nr*ntau*nq,1))
ZT = np.sort(ZT,axis=1)
ZT = np.tile(np.expand_dims(ZT,axis=1),(nzp,1))

ZT_ind = np.tile(np.expand_dims(zt_grid_ind,axis=1),(nr*ntau*nq,1))
ZT_ind = np.sort(ZT_ind,axis=1)
ZT_ind = np.tile(np.expand_dims(ZT_ind,axis=1),(nzp,1))

# Create matrices for ZP and ZP_ind
ZP = np.tile(np.expand_dims(zp_grid,axis=1),(nzt*nr*ntau*nq,1))
ZP = np.sort(ZP,axis=1)
ZP = ZP.reshape(-1,1)

ZP_ind = np.tile(np.expand_dims(zp_grid_ind,axis=1),(nzt*nr*ntau*nq,1))
ZP_ind = np.sort(ZP_ind,axis=1)

# Her er problemet
EXOG =[ZP,ZT,R,TAU,Q]
EXOG_ind = [ZP_ind,ZT_ind,R_ind,TAU_ind,Q_ind]

In [68]:
EXOG = np.column_stack((ZP, ZT, R, TAU, Q))

# Concatenate ZP_ind, ZT_ind, R_ind, TAU_ind, and Q_ind along the columns to form EXOG_ind
EXOG_ind = np.column_stack((ZP_ind, ZT_ind, R_ind, TAU_ind, Q_ind))

# Transpose EXOG and EXOG_ind
EXOG = EXOG.T
EXOG_ind = EXOG_ind.T


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)

In [65]:
print(ZP)

[[0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86000091]
 [0.78499977]
 [1.86

In [66]:
print(ZT)

[[[-0.49599212]
  [-0.49599212]]

 [[-0.39938612]
  [-0.39938612]]

 [[-0.30278012]
  [-0.30278012]]

 [[-0.20617412]
  [-0.20617412]]

 [[-0.10956811]
  [-0.10956811]]

 [[-0.01296211]
  [-0.01296211]]

 [[ 0.08364389]
  [ 0.08364389]]

 [[ 0.18024989]
  [ 0.18024989]]

 [[ 0.2768559 ]
  [ 0.2768559 ]]

 [[ 0.3734619 ]
  [ 0.3734619 ]]

 [[ 0.4700679 ]
  [ 0.4700679 ]]

 [[-0.49599212]
  [-0.49599212]]

 [[-0.39938612]
  [-0.39938612]]

 [[-0.30278012]
  [-0.30278012]]

 [[-0.20617412]
  [-0.20617412]]

 [[-0.10956811]
  [-0.10956811]]

 [[-0.01296211]
  [-0.01296211]]

 [[ 0.08364389]
  [ 0.08364389]]

 [[ 0.18024989]
  [ 0.18024989]]

 [[ 0.2768559 ]
  [ 0.2768559 ]]

 [[ 0.3734619 ]
  [ 0.3734619 ]]

 [[ 0.4700679 ]
  [ 0.4700679 ]]

 [[-0.49599212]
  [-0.49599212]]

 [[-0.39938612]
  [-0.39938612]]

 [[-0.30278012]
  [-0.30278012]]

 [[-0.20617412]
  [-0.20617412]]

 [[-0.10956811]
  [-0.10956811]]

 [[-0.01296211]
  [-0.01296211]]

 [[ 0.08364389]
  [ 0.08364389]]

 [[ 0.18024989

In [50]:
# Combine a_grid and k_grid for vectorization purposes
A = np.tile(np.expand_dims(a_grid,axis=1),(nk,1))
A = np.sort(A,axis=1)
K = np.tile(np.expand_dims(k_grid,axis=1),(na,1))
G = np.column_stack((A,K))


array([[0.01      , 0.01      ],
       [0.03512605, 0.06033613],
       [0.0602521 , 0.11067227],
       ...,
       [2.9497479 , 5.89932773],
       [2.97487395, 5.94966387],
       [3.        , 6.        ]])

In [55]:
# Probability of transitioning from some (zt,zp,tau,r) to some (zt,zp,tau,r)
prob = np.zeros((n_state,n_state))

# Iterate over each state 
for i_state in range(n_state):
    izp = EXOG_ind[0,i_state]
    izt = EXOG_ind[1,i_state]
    ir  = EXOG_ind[2,i_state]
    itau= EXOG_ind[3,i_state]
    iq  = EXOG_ind[4,i_state]

    # Iterate over next states
    for i_state_next in range(n_state):
        izpnext = EXOG_ind[0,i_state_next]
        iztnext = EXOG_ind[1,i_state_next]
        izrnext = EXOG_ind[2,i_state_next]
        itaunext= EXOG_ind[3,i_state_next]
        iqnext  = EXOG_ind[4,i_state_next]

        prob[i_state,i_state_next] = ztprob[izt,iztnext] * zpprob[izp,izpnext] * rprob[ir,irnext]* tauprob[itau,itaunext]*qprob[iq,iqnext]



TypeError: list indices must be integers or slices, not tuple